name: 'radar_combustiveis'
version: '1.0.0'
config-version: 2

profile: 'radar_combustiveis'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  radar_combustiveis:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
